version: '3'

networks:
  backend:
  frontend:

services:
  firstservice:
    image: firstservice
    build:
      context: .
      dockerfile: FirstService/Dockerfile
    ports:
     - "8181:80"
    networks:
     - backend

  secondservice:
    image: secondservice
    build:
      context: .
      dockerfile: SecondService/Dockerfile
    ports:
     - "8182:80"
    networks:
     - backend

