version: '3'

services:
  firstservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  oauthserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

