version: '3'

networks:
  backend:
  frontend:

services:
  firstservice:
    image: firstservice
    build:
      context: .
      dockerfile: FirstService/Dockerfile
    ports:
     - "8181:80"
    networks:
     - backend

  consumerservice:
    image: consumerservice
    build:
      context: .
      dockerfile: ConsumerService/Dockerfile
    ports:
     - "8182:80"
    networks:
     - backend

  oauthserver:
    image: oauthserver
    build:
      context: .
      dockerfile: OAuthServer/Dockerfile
    ports:
      - "8183:80"
    networks:
      - backend

  redis:
    image: redis
    ports:
      - "8184:6379"
    networks:
      - backend

  mongo:
    image: mongo
    ports: 
      - "8185:27017"
    networks:
      - backend

  rabbitmq:
    image: rabbitmq
    #command: /bin/bash -c "rabbitmq-plugins enable rabbitmq_management"
    ports:
      - "8186:5672"
      - "8187:15672" #dashboard
    networks:
     - backend

