version: '3'

networks:
  backend:
  frontend:

services:
  firstservice:
    image: firstservice
    build:
      context: .
      dockerfile: FirstService/Dockerfile
    ports:
     - "8181:80"
    networks:
     - backend

  secondservice:
    image: secondservice
    build:
      context: .
      dockerfile: SecondService/Dockerfile
    ports:
     - "8182:80"
    networks:
     - backend

  oauthserver:
    image: oauthserver
    build:
      context: .
      dockerfile: OAuthServer/Dockerfile
    ports:
      - "8183:80"
    networks:
      - backend

  redis:
    image: redis
    ports:
      - "8184:6379"
    networks:
      - backend

  mongo:
    image: mongo
    ports: 
      - "8185:27017"
    networks:
      - backend

  rabbitmq:
    image: rabbitmq
    ports:
      - "8186:5673"
    networks:
     - backend