version: '3'

networks:
  backend:

services:
  firstservice:
    image: firstservice
    build:
      context: .
      dockerfile: FirstService/Dockerfile
    ports:
     - "8181:80"
    networks:
     - backend
    #restart: always
    depends_on:
      - "rabbitmq"
      - "redis"

  consumerservice:
    image: consumerservice
    build:
      context: .
      dockerfile: ConsumerService/Dockerfile
    networks:
     - backend
    #restart: always
    depends_on:
      - "rabbitmq"
      - "mongo"

  oauthserver:
    image: oauthserver
    build:
      context: .
      dockerfile: OAuthServer/Dockerfile
    ports:
      - "8183:80"
    networks:
      - backend

  redis:
    image: redis
    ports:
      - "8184:6379"
    networks:
      - backend

  mongo:
    image: mongo
    ports: 
      - "8185:27017"
    networks:
      - backend

  rabbitmq:
    image: rabbitmq
    #command: /bin/bash -c "rabbitmq-plugins enable rabbitmq_management"
    ports:
      - "5672:5672"
      - "8187:15672" #dashboard
    networks:
     - backend

