version: '3'

services:
  firstservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "80"

  oauthserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "80"

  consumerservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
