version: '3'

networks:
  backend:
  frontend:

services:
  firstservice:
    image: firstservice
    build:
      context: .
      dockerfile: FirstService/Dockerfile
    ports:
     - "85:80"
    networks:
     - backend
